site_name: Lingtrain Docs
site_url: https://lingtra.in/docs
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - content.tabs.link

markdown_extensions:
  - attr_list
  - toc:
      permalink: true

plugins:
  - search
  - i18n:
      languages:
        - locale: en
          name: English
          build: true
          default: true
          nav:
            - Getting started:
              - Overview: index.md
              - Uploading texts: uploading.md
              - Alignment process: alignment.md
              - Proxy texts: proxy.md
              - Export: export.md
            - Python library:
              - lingtrain-aligner: python-library.md
              - Alignment algorithm: algorithm.md
        - locale: ru
          name: Russian
          build: true
          nav:
            - Начало работы:
              - Обзор: index.md
              - Загрузка текстов: uploading.md
              - Процесс выравнивания: alignment.md
              - Подстрочник: proxy.md
              - Экспорт: export.md
            - Библиотека Python:
              - lingtrain-aligner: python-library.md
              - Алгоритм выравнивания: algorithm.md

nav:
  - Getting started:
    - Overview: index.md
    - Uploading texts: uploading.md
    - Alignment process: alignment.md
    - Proxy texts: proxy.md
    - Export: export.md
  - Python library:
    - lingtrain-aligner: python-library.md
    - Alignment algorithm: algorithm.md
